POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Hola soy uaco",
    "important": false
}

###


POST http://localhost:3001/api/notes 
Content-Type: application/json

{
}
