POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Hola soy Pau, la novia mas linda v.v",
    "important": true
}

###


POST http://localhost:3001/api/notes 
Content-Type: application/json

{
}
